// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4UNivVvBx579mTny6fSAxobiHZ3aS9c8',
    appId: '1:306515254042:web:2eba771c8ba1980e72aaa3',
    messagingSenderId: '306515254042',
    projectId: 'recuerda-facil',
    authDomain: 'recuerda-facil.firebaseapp.com',
    storageBucket: 'recuerda-facil.appspot.com',
    measurementId: 'G-HC9V81B7TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFHPMbxLyr_GIciZ0uFIr0ndwUT8zzIC4',
    appId: '1:306515254042:android:2c1c9d6ad90f0b5972aaa3',
    messagingSenderId: '306515254042',
    projectId: 'recuerda-facil',
    storageBucket: 'recuerda-facil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB78SdaZBXNTJuT6O8E-_2dFjCayqw1dyU',
    appId: '1:306515254042:ios:c6f1daca1b6a1bf572aaa3',
    messagingSenderId: '306515254042',
    projectId: 'recuerda-facil',
    storageBucket: 'recuerda-facil.appspot.com',
    iosClientId: '306515254042-a505phq754d7i6qdsb8mudcp4tq81t0q.apps.googleusercontent.com',
    iosBundleId: 'com.recuerdafacil.recuerdaFacil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB78SdaZBXNTJuT6O8E-_2dFjCayqw1dyU',
    appId: '1:306515254042:ios:edc48f4a93ba1b1f72aaa3',
    messagingSenderId: '306515254042',
    projectId: 'recuerda-facil',
    storageBucket: 'recuerda-facil.appspot.com',
    iosClientId: '306515254042-8itqnlujku61rc21cpivmjtjkl9goh1f.apps.googleusercontent.com',
    iosBundleId: 'com.recuerdafacil.recuerdaFacil.RunnerTests',
  );
}
